<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sample.AspNetCore.ServiceDefaults\Sample.AspNetCore.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\src\Durably.Persistence.EntityFrameworkCore\Durably.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Durably.Traceability\Durably.Traceability.csproj" />
    <ProjectReference Include="..\..\src\Durably.UI\Durably.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <DurablyUiWwwRoot
      Include="..\..\src\Durably.UI\wwwroot\**\*" />
  </ItemGroup>

  <Target Name="CopyDurablyUiWwwRoot" AfterTargets="Build">
    <Copy
      SourceFiles="@(DurablyUiWwwRoot)"
      DestinationFiles="@(DurablyUiWwwRoot->'$(OutDir)wwwroot\%(RecursiveDir)%(Filename)%(Extension)')"
      SkipUnchangedFiles="true" />
  </Target>

</Project>
