<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Durably.TestSupport\Durably.TestSupport.csproj" />
    <ProjectReference Include="..\..\src\Durably.Persistence.EntityFrameworkCore\Durably.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="..\..\src\Durably.Traceability\Durably.Traceability.csproj" />
  </ItemGroup>

</Project>
